default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_app_rails_development
  username: postgres
  password: <%= ENV['DB_password'] %>

test:
  <<: *default
  database: Blog_app_rails_test
  username: postgres
  password: <%= ENV['DB_password'] %>

production:
  <<: *default
  database: Blog_app_rails_production
  username: postgres
  password: <%= ENV['DB_password'] %>
